### ISSUE TITLE
Windows: createTempFile doesn't work when C:\Temp does not exist (fixed in GraalVM 20)

### ISSUE THREAD

**Issue by borkdude** [borkdude/babashka#352]
Repro, delete `C:\Temp` if it already exists. Then compile this class to a native binary:

``` java
public class TempFile {
    public static void main(String [] args) throws java.io.IOException {
        java.io.File f = java.io.File.createTempFile("foo", "bar");
        System.out.println(f.exists());
        System.out.println(f.getPath());
    }
}
```

**Comment by sogaiu** [comment]
On Windows 10 with graalvm-ce java8 19.3.1, I get:
```
C:\Users\user\Desktop\borkdude>native-image.cmd TempFile
[tempfile:4504]    classlist:   1,708.00 ms
[tempfile:4504]        (cap):   2,188.67 ms
[tempfile:4504]        setup:   3,255.26 ms
[tempfile:4504]   (typeflow):   6,697.86 ms
[tempfile:4504]    (objects):   7,376.68 ms
[tempfile:4504]   (features):     305.36 ms
[tempfile:4504]     analysis:  14,698.82 ms
[tempfile:4504]     (clinit):     123.30 ms
[tempfile:4504]     universe:     405.47 ms
[tempfile:4504]      (parse):     567.00 ms
[tempfile:4504]     (inline):   1,423.94 ms
[tempfile:4504]    (compile):   4,925.68 ms
[tempfile:4504]      compile:   7,287.90 ms
[tempfile:4504]        image:     536.16 ms
[tempfile:4504]        write:     718.01 ms
[tempfile:4504]      [total]:  28,943.77 ms

C:\Users\user\Desktop\borkdude>.\tempfile.exe
true
C:\Temp\foo7246420273330864528bar
```

**Comment by sogaiu** [comment]
On Windows 10 with with graalvm-ce java8 20.0.0, I get:
```
C:\Users\user\Desktop\borkdude>native-image.cmd TempFile
[tempfile:7836]    classlist:   1,888.65 ms,  1.18 GB
[tempfile:7836]        (cap):   1,427.60 ms,  1.18 GB
[tempfile:7836]        setup:   2,724.39 ms,  1.18 GB
[tempfile:7836]   (typeflow):   6,601.23 ms,  1.28 GB
[tempfile:7836]    (objects):   7,254.63 ms,  1.28 GB
[tempfile:7836]   (features):     262.56 ms,  1.28 GB
[tempfile:7836]     analysis:  14,495.63 ms,  1.28 GB
[tempfile:7836]     (clinit):     131.19 ms,  1.83 GB
[tempfile:7836]     universe:     909.47 ms,  1.83 GB
[tempfile:7836]      (parse):     605.52 ms,  1.83 GB
[tempfile:7836]     (inline):     929.64 ms,  1.90 GB
[tempfile:7836]    (compile):   4,534.36 ms,  2.08 GB
[tempfile:7836]      compile:   6,390.97 ms,  2.08 GB
[tempfile:7836]        image:     555.99 ms,  2.08 GB
[tempfile:7836]        write:     367.48 ms,  2.08 GB
[tempfile:7836]      [total]:  27,628.30 ms,  2.08 GB

C:\Users\user\Desktop\borkdude>.\tempfile.exe
true
C:\Users\user\AppData\Local\Temp\foo9061871425086026647bar
```

**Comment by borkdude** [comment]
Thanks! 
@sogaiu Did you delete the `C:\Temp` directory prior to executing the binary?

**Comment by sogaiu** [comment]
No, should I do that and try again?

**Comment by borkdude** [comment]
For 19.3.1 that would be nice to try yes. 

> Repro, delete C:\Temp if it already exists. Then compile this class to a native binary:

That was the issue I ran into with babashka.curl on a system where `C:\Temp` did not exist. The requests fail for that reason.

**Comment by sogaiu** [comment]
Ah, yes, I failed to read that correctly.  Sorry, I'll try again.

**Comment by sogaiu** [comment]
Bingo:
```
C:\Users\user\Desktop\borkdude>native-image.cmd TempFile
[tempfile:2392]    classlist:   1,396.43 ms
[tempfile:2392]        (cap):   1,572.46 ms
[tempfile:2392]        setup:   2,640.52 ms
[tempfile:2392]   (typeflow):   6,609.90 ms
[tempfile:2392]    (objects):   7,253.97 ms
[tempfile:2392]   (features):     237.77 ms
[tempfile:2392]     analysis:  14,450.69 ms
[tempfile:2392]     (clinit):     131.49 ms
[tempfile:2392]     universe:     432.72 ms
[tempfile:2392]      (parse):     510.10 ms
[tempfile:2392]     (inline):   1,728.92 ms
[tempfile:2392]    (compile):   5,097.92 ms
[tempfile:2392]      compile:   7,683.11 ms
[tempfile:2392]        image:     566.94 ms
[tempfile:2392]        write:     313.00 ms
[tempfile:2392]      [total]:  27,752.74 ms

C:\Users\user\Desktop\borkdude>.\tempfile.exe
Exception in thread "main" java.io.IOException: The system cannot find the path specified
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_io_IOException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
        at java.io.WinNTFileSystem.createFileExclusively(WinNTFileSystem.java)
        at java.io.File.createTempFile(File.java:2024)
        at java.io.File.createTempFile(File.java:2070)
        at TempFile.main(TempFile.java:3)
```

**Comment by borkdude** [comment]
@sogaiu Thanks!

**Comment by borkdude** [comment]
Fixed.
