### ISSUE TITLE
babashka now seems to require Java 11, can't compile on graalvm8

### ISSUE THREAD

**Issue by bennyandresen** [borkdude/babashka#480]
**version**

version 1.0.2

**platform**

Linux (NixOS 20.3)

**problem**

Can't compile babashka since move to GraalVM11 20.1

**repro**

Compiling using GraalVM8 19.2.1

```
Error: Class initialization of babashka.main failed. Use the option --initialize-at-run-time=babashka.main to explicitly request delayed initialization of this class.
Detailed message:

com.oracle.svm.core.util.UserError$UserException: Class initialization of babashka.main failed. Use the option --initialize-at-run-time=babashka.main to explicitly request delayed initialization of this class.
Detailed message:

        at com.oracle.svm.core.util.UserError.abort(UserError.java:75)
        at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:223)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:737)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:526)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Class initialization of babashka.main failed. Use the option --initialize-at-run-time=babashka.main to explicitly request delayed initialization of this class.
Detailed message:

        at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:130)
        at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:565)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:688)
        ... 7 more
Caused by: java.lang.UnsupportedClassVersionError: sci/impl/Reflector has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at clojure.lang.RT.classForName(RT.java:2211)
        at clojure.lang.RT.classForNameNonLoading(RT.java:2224)
        at sci.impl.interop$loading__6725__auto____8098.invoke(interop.cljc:1)
        at sci.impl.interop__init.load(Unknown Source)
        at sci.impl.interop__init.<clinit>(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at clojure.lang.RT.classForName(RT.java:2211)
        at clojure.lang.RT.classForName(RT.java:2220)
        at clojure.lang.RT.loadClassForName(RT.java:2239)
        at clojure.lang.RT.load(RT.java:449)
        at clojure.lang.RT.load(RT.java:424)
        at clojure.core$load$fn__6844.invoke(core.clj:6128)
        at clojure.core$load.invokeStatic(core.clj:6127)
        at clojure.core$load.doInvoke(core.clj:6111)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5910)
[...]
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1447)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1225)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1187)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1146)
```

**expected behavior**

An explicit documentation that GraalVM11 is required, or maybe this `java.lang.UnsupportedClassVersionError: sci/impl/Reflector` could be supplied from GraalVM8 instead?

**Comment by borkdude** [comment]
@bennyandresen That is already documented, here: https://github.com/borkdude/babashka/blob/master/doc/build.md

**Comment by bennyandresen** [comment]
I didn't read this as a hard dependency, which it didn't use to be.

Thanks for the pointer. :-)
